// Kuratert utvalg til Børs-screeneren — håndplukket, ikke søkeord-avledet.
// Asiatiske selskaper bruker ADR der det finnes en likvid en (bedre datakvalitet
// fra Yahoo enn native tickere), ellers primær hjemmebørs.
export const BORS_UNIVERS = [
  // ---- Norge (Oslo Børs — hele hovedlisten, hentet fra Euronext) ----
  { navn: '2020 Bulkers', ticker: '2020.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'ABG Sundal Collier', ticker: 'ABG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'AF Gruppen', ticker: 'AFG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Agilyx', ticker: 'AGLX.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Akastor', ticker: 'AKAST.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Aker', ticker: 'AKER.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Aker BioMarine', ticker: 'AKBM.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'Aker BP', ticker: 'AKRBP.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Aker Solutions', ticker: 'AKSO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'AKVA Group', ticker: 'AKVA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'Appear', ticker: 'APR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Aqualis', ticker: 'AQUA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Archer', ticker: 'ARCH.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'ArcticZymes Technologies', ticker: 'AZT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Arendals Fossekompani', ticker: 'AFK.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Arribatec Group', ticker: 'ARR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Atea', ticker: 'ATEA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Atlantic Sapphire TR', ticker: 'ASAS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'Atlantic Sapphire', ticker: 'ASA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'Aurskog Sparebank', ticker: 'AURG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Austevoll Seafood', ticker: 'AUSS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'AutoStore Holdings', ticker: 'AUTO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Axactor', ticker: 'ACR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'B2 Impact', ticker: 'B2I.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Bakkafrost', ticker: 'BAKKA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'Bevest', ticker: 'BINT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'BEWi', ticker: 'BEWI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Bien Sparebank', ticker: 'BIEN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'BlueNord', ticker: 'BNOR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Bohus', ticker: 'BOHUS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'Bonheur', ticker: 'BONHR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Borgestad', ticker: 'BOR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Borr Drilling', ticker: 'BORR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Borregaard', ticker: 'BRG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Bouvet', ticker: 'BOUV.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'BW Energy', ticker: 'BWE.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'BW LPG', ticker: 'BWLPG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'BW Offshore', ticker: 'BWO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Cadeler', ticker: 'CADLR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Capsol Technologies', ticker: 'CAPSL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Cavendish Hydrogen', ticker: 'CAVEN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Circio Holding', ticker: 'CRNA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Cloudberry Clean Energy', ticker: 'CLOUD.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'CMB.TECH', ticker: 'CMBTO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Constellation Oil Services', ticker: 'COSH.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'ContextVision', ticker: 'CONTX.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Dellia Group', ticker: 'DELIA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'DNB Bank', ticker: 'DNB.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'DNO', ticker: 'DNO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'DOF Group', ticker: 'DOFG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Eidesvik Offshore', ticker: 'EIOF.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Elkem', ticker: 'ELK.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Elliptic Laboratories', ticker: 'ELABS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Elmera Group', ticker: 'ELMRA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Elopak', ticker: 'ELO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Endúr', ticker: 'ENDUR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'enSurge Micropower', ticker: 'ENSU.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Entra', ticker: 'ENTRA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'eiendom' },
  { navn: 'Envipco Holding', ticker: 'ENVIP.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Equinor', ticker: 'EQNR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'EQVA', ticker: 'EQVA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Europris', ticker: 'EPR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'Fjord Defence Group', ticker: 'DFENS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Frontline', ticker: 'FRO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'General Oceans', ticker: 'GENO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Gentian Diagnostics', ticker: 'GENT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Gjensidige Forsikring', ticker: 'GJF.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Goodtech', ticker: 'GOD.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Grieg Seafood', ticker: 'GSF.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'Gyldendal', ticker: 'GYL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'Hafnia', ticker: 'HAFNI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Haugesund Sparebank', ticker: 'HGSB.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Havila Shipping', ticker: 'HAVI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Hermana Holding', ticker: 'HERMA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Hexagon Composites', ticker: 'HEX.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Hexagon Purus', ticker: 'HPUR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Himalaya Shipping', ticker: 'HSHP.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Hofseth BioCare', ticker: 'HBC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'HydrogenPro', ticker: 'HYPRO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Höegh Autoliners', ticker: 'HAUTO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Høland og Setskog Sparebank', ticker: 'HSPG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'IDEX Biometrics', ticker: 'IDEX.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Integrated Wind Solutions', ticker: 'IWS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'InterOil Exploration and Production', ticker: 'IOX.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Itera', ticker: 'ITERA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Jinhui Shipping and Transportation', ticker: 'JIN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Jæren Sparebank', ticker: 'JAREN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Kid', ticker: 'KID.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'Kitron', ticker: 'KIT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Klaveness Combination Carriers', ticker: 'KCC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Komplett', ticker: 'KOMPL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'Kongsberg Automotive', ticker: 'KOA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Kongsberg Gruppen', ticker: 'KOG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Kongsberg Maritime', ticker: 'KMAR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Lerøy Seafood Group', ticker: 'LSG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'LifeCare', ticker: 'LIFE.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Link Mobility Group', ticker: 'LINK.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'telekom' },
  { navn: 'Magnora', ticker: 'MGN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Medistim', ticker: 'MEDI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Melhus Sparebank', ticker: 'MELG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Moreld', ticker: 'MORLD.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Mowi', ticker: 'MOWI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'MPC Container Ships', ticker: 'MPCC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Multiconsult', ticker: 'MULTI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Napatech', ticker: 'NAPA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Navamedic', ticker: 'NAVA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Nekkar', ticker: 'NKR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Nel', ticker: 'NEL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Next Biometrics Group', ticker: 'NEXT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Norbit', ticker: 'NORBT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Norconsult', ticker: 'NORCO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Nordic Mining', ticker: 'NOM.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Nordic Semiconductor', ticker: 'NOD.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Norsk Hydro', ticker: 'NHY.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Norske Skog', ticker: 'NSKOG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Northern Ocean', ticker: 'NOL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Norwegian Air Shuttle', ticker: 'NAS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'NRC Group', ticker: 'NRC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Nykode Therapeutics', ticker: 'NYKD.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Odfjell Drilling', ticker: 'ODL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Odfjell SE A', ticker: 'ODF.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Odfjell SE B', ticker: 'ODFB.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Odfjell Technology', ticker: 'OTL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'OKEA', ticker: 'OKEA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Okeanis Eco Tankers', ticker: 'OET.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Oncoinvent', ticker: 'ONCIN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Orkla', ticker: 'ORK.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'Otello Corporation', ticker: 'OTEC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Otovo', ticker: 'OTOVO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Panoro Energy', ticker: 'PEN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Paratus Energy Services', ticker: 'PLSV.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Pareto Bank', ticker: 'PARB.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Petrolia', ticker: 'PSE.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'PetroNor E&P', ticker: 'PNOR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Pexip Holding', ticker: 'PEXIP.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Photocure', ticker: 'PHO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Polaris Media', ticker: 'POL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'poLight', ticker: 'PLT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'PPI Public Property Invest', ticker: 'PUBLI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'eiendom' },
  { navn: 'Prosafe', ticker: 'PRS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Protector Forsikring', ticker: 'PROT.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Questerre Energy', ticker: 'QEC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Reach Subsea', ticker: 'REACH.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Rogaland Sparebank', ticker: 'ROGS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'S.D. Standard ETC', ticker: 'SDSD.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Saga Pure', ticker: 'SAGA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'SalMar', ticker: 'SALM.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'Salmon Evolution', ticker: 'SALME.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'sjomat' },
  { navn: 'SATS', ticker: 'SATS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'forbruk' },
  { navn: 'Scana', ticker: 'SCANA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Scatec', ticker: 'SCATC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'SED Energy Holdings', ticker: 'ENH.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Selvaag Bolig', ticker: 'SBO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'eiendom' },
  { navn: 'Sentia', ticker: 'SNTIA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Skue Sparebank', ticker: 'SKUE.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SmartOptics Group', ticker: 'SMOP.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'SoftwareOne Holding', ticker: 'SWON.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Sogn Sparebank', ticker: 'SOGN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Soiltech', ticker: 'STECH.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Solstad Maritime', ticker: 'SOMA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Solstad Offshore', ticker: 'SOFF.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'SpareBank 1 SMN', ticker: 'MING.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SpareBank 1 Sør-Norge', ticker: 'SB1NO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Sparebanken Møre', ticker: 'MORG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Sparebanken Norge', ticker: 'SBNOR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Sparebanken Øst', ticker: 'SPOG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SpareBank 1 Nordmøre', ticker: 'SNOR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SpareBank 1 Østlandet', ticker: 'SPOL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SpareBank 1 Helgeland', ticker: 'HELG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SpareBank 1 Nord-Norge', ticker: 'NONG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SpareBank 1 Ringerike Hadeland', ticker: 'RING.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'SpareBank 1 Østfold Akershus', ticker: 'SOAG.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Stolt-Nielsen', ticker: 'SNI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Storebrand', ticker: 'STB.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'StrongPoint', ticker: 'STRO.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Subsea 7', ticker: 'SUBC.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Techstep', ticker: 'TECH.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Tekna Holding', ticker: 'TEKNA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Telenor', ticker: 'TEL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'telekom' },
  { navn: 'TGS', ticker: 'TGS.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Thor Medical', ticker: 'TRMED.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Tomra Systems', ticker: 'TOM.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Trøndelag Sparebank', ticker: 'TRSB.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'Veidekke', ticker: 'VEI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Vend Marketplaces', ticker: 'VEND.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Vistin Pharma', ticker: 'VISTN.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },
  { navn: 'Voim', ticker: 'VOIM.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Voss Veksel- og Landmandsbank', ticker: 'VVL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'finans' },
  { navn: 'VOW', ticker: 'VOW.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Vår Energi', ticker: 'VAR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'energi' },
  { navn: 'Wallenius Wilhelmsen', ticker: 'WAWI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Webstep', ticker: 'WSTEP.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Wilh. Wilhelmsen Holding A', ticker: 'WWI.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Wilh. Wilhelmsen Holding B', ticker: 'WWIB.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'shipping' },
  { navn: 'Yara International', ticker: 'YAR.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'industri' },
  { navn: 'Zalaris', ticker: 'ZAL.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'teknologi' },
  { navn: 'Zaptec', ticker: 'ZAP.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'fornybar' },
  { navn: 'Zelluna', ticker: 'ZLNA.OL', marked: 'no', bors: 'Oslo Børs', sektor: 'helse' },

  // ---- USA ----
  { navn: 'Apple', ticker: 'AAPL', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Microsoft', ticker: 'MSFT', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Alphabet', ticker: 'GOOGL', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Amazon', ticker: 'AMZN', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Meta Platforms', ticker: 'META', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Nvidia', ticker: 'NVDA', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Broadcom', ticker: 'AVGO', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Oracle', ticker: 'ORCL', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Salesforce', ticker: 'CRM', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Adobe', ticker: 'ADBE', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Intel', ticker: 'INTC', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'AMD', ticker: 'AMD', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Cisco', ticker: 'CSCO', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'IBM', ticker: 'IBM', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Netflix', ticker: 'NFLX', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'JPMorgan Chase', ticker: 'JPM', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Bank of America', ticker: 'BAC', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Wells Fargo', ticker: 'WFC', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Goldman Sachs', ticker: 'GS', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Morgan Stanley', ticker: 'MS', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Visa', ticker: 'V', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Mastercard', ticker: 'MA', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Berkshire Hathaway', ticker: 'BRK-B', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Johnson & Johnson', ticker: 'JNJ', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Pfizer', ticker: 'PFE', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'UnitedHealth', ticker: 'UNH', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'AbbVie', ticker: 'ABBV', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Merck', ticker: 'MRK', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Eli Lilly', ticker: 'LLY', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Walmart', ticker: 'WMT', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Procter & Gamble', ticker: 'PG', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Coca-Cola', ticker: 'KO', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'PepsiCo', ticker: 'PEP', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'McDonald\'s', ticker: 'MCD', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Nike', ticker: 'NKE', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Starbucks', ticker: 'SBUX', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Home Depot', ticker: 'HD', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Disney', ticker: 'DIS', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Costco', ticker: 'COST', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'ExxonMobil', ticker: 'XOM', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Chevron', ticker: 'CVX', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Boeing', ticker: 'BA', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Caterpillar', ticker: 'CAT', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'General Electric', ticker: 'GE', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Honeywell', ticker: 'HON', marked: 'us', bors: 'NASDAQ', sektor: 'industri' },
  { navn: 'AT&T', ticker: 'T', marked: 'us', bors: 'NYSE', sektor: 'telekom' },
  { navn: 'Verizon', ticker: 'VZ', marked: 'us', bors: 'NYSE', sektor: 'telekom' },

  { navn: 'Accenture', ticker: 'ACN', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Autodesk', ticker: 'ADSK', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Akamai Technologies', ticker: 'AKAM', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Applied Materials', ticker: 'AMAT', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Arista Networks', ticker: 'ANET', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Amphenol', ticker: 'APH', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'AppLovin', ticker: 'APP', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Cadence Design Systems', ticker: 'CDNS', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'CrowdStrike', ticker: 'CRWD', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Cognizant', ticker: 'CTSH', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Datadog', ticker: 'DDOG', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Dell Technologies', ticker: 'DELL', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Fair Isaac (FICO)', ticker: 'FICO', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Fortinet', ticker: 'FTNT', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'GoDaddy', ticker: 'GDDY', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Corning', ticker: 'GLW', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Hewlett Packard Enterprise', ticker: 'HPE', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'HP Inc.', ticker: 'HPQ', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'Intuit', ticker: 'INTU', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Keysight Technologies', ticker: 'KEYS', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'KLA Corporation', ticker: 'KLAC', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Lam Research', ticker: 'LRCX', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Marvell Technology', ticker: 'MRVL', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Palo Alto Networks', ticker: 'PANW', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Qualcomm', ticker: 'QCOM', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Synopsys', ticker: 'SNPS', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'TE Connectivity', ticker: 'TEL', marked: 'us', bors: 'NYSE', sektor: 'teknologi' },
  { navn: 'The Trade Desk', ticker: 'TTD', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Texas Instruments', ticker: 'TXN', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Zoom Communications', ticker: 'ZM', marked: 'us', bors: 'NASDAQ', sektor: 'teknologi' },
  { navn: 'Charter Communications', ticker: 'CHTR', marked: 'us', bors: 'NASDAQ', sektor: 'telekom' },
  { navn: 'Comcast', ticker: 'CMCSA', marked: 'us', bors: 'NASDAQ', sektor: 'telekom' },
  { navn: 'T-Mobile US', ticker: 'TMUS', marked: 'us', bors: 'NASDAQ', sektor: 'telekom' },
  { navn: 'Abbott Laboratories', ticker: 'ABT', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Amgen', ticker: 'AMGN', marked: 'us', bors: 'NASDAQ', sektor: 'helse' },
  { navn: 'Becton Dickinson', ticker: 'BDX', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Boston Scientific', ticker: 'BSX', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Bristol Myers Squibb', ticker: 'BMY', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Cigna', ticker: 'CI', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'CVS Health', ticker: 'CVS', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Danaher', ticker: 'DHR', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Elevance Health', ticker: 'ELV', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Gilead Sciences', ticker: 'GILD', marked: 'us', bors: 'NASDAQ', sektor: 'helse' },
  { navn: 'HCA Healthcare', ticker: 'HCA', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Humana', ticker: 'HUM', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Intuitive Surgical', ticker: 'ISRG', marked: 'us', bors: 'NASDAQ', sektor: 'helse' },
  { navn: 'McKesson', ticker: 'MCK', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Medtronic', ticker: 'MDT', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Regeneron Pharmaceuticals', ticker: 'REGN', marked: 'us', bors: 'NASDAQ', sektor: 'helse' },
  { navn: 'Stryker', ticker: 'SYK', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Thermo Fisher Scientific', ticker: 'TMO', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Vertex Pharmaceuticals', ticker: 'VRTX', marked: 'us', bors: 'NASDAQ', sektor: 'helse' },
  { navn: 'Zimmer Biomet', ticker: 'ZBH', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'Zoetis', ticker: 'ZTS', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'IQVIA', ticker: 'IQV', marked: 'us', bors: 'NYSE', sektor: 'helse' },
  { navn: 'American Express', ticker: 'AXP', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'American International Group', ticker: 'AIG', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Aon', ticker: 'AON', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Blackstone', ticker: 'BX', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Citigroup', ticker: 'C', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Chubb', ticker: 'CB', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'CME Group', ticker: 'CME', marked: 'us', bors: 'NASDAQ', sektor: 'finans' },
  { navn: 'Capital One', ticker: 'COF', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Global Payments', ticker: 'GPN', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Intercontinental Exchange', ticker: 'ICE', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'KKR & Co.', ticker: 'KKR', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'MetLife', ticker: 'MET', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'M&T Bank', ticker: 'MTB', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Progressive', ticker: 'PGR', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Prudential Financial', ticker: 'PRU', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Charles Schwab', ticker: 'SCHW', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'S&P Global', ticker: 'SPGI', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Truist Financial', ticker: 'TFC', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Travelers', ticker: 'TRV', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'U.S. Bancorp', ticker: 'USB', marked: 'us', bors: 'NYSE', sektor: 'finans' },
  { navn: 'Airbnb', ticker: 'ABNB', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'AutoZone', ticker: 'AZO', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Booking Holdings', ticker: 'BKNG', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Carnival Corporation', ticker: 'CCL', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Chipotle Mexican Grill', ticker: 'CMG', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Deckers Brands', ticker: 'DECK', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'eBay', ticker: 'EBAY', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Expedia Group', ticker: 'EXPE', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Ford Motor Company', ticker: 'F', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'General Motors', ticker: 'GM', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Hilton Worldwide', ticker: 'HLT', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Lululemon Athletica', ticker: 'LULU', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Las Vegas Sands', ticker: 'LVS', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Marriott International', ticker: 'MAR', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: "O'Reilly Automotive", ticker: 'ORLY', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Royal Caribbean', ticker: 'RCL', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Ross Stores', ticker: 'ROST', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Target', ticker: 'TGT', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Colgate-Palmolive', ticker: 'CL', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Dollar General', ticker: 'DG', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Estée Lauder Companies', ticker: 'EL', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'General Mills', ticker: 'GIS', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Hershey Company', ticker: 'HSY', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Kraft Heinz', ticker: 'KHC', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'Kimberly-Clark', ticker: 'KMB', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Altria', ticker: 'MO', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Constellation Brands', ticker: 'STZ', marked: 'us', bors: 'NYSE', sektor: 'forbruk' },
  { navn: 'Walgreens Boots Alliance', ticker: 'WBA', marked: 'us', bors: 'NASDAQ', sektor: 'forbruk' },
  { navn: 'American Tower', ticker: 'AMT', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'AvalonBay Communities', ticker: 'AVB', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'CBRE Group', ticker: 'CBRE', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'Crown Castle', ticker: 'CCI', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'Digital Realty', ticker: 'DLR', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'Equinix', ticker: 'EQIX', marked: 'us', bors: 'NASDAQ', sektor: 'eiendom' },
  { navn: 'Prologis', ticker: 'PLD', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'Public Storage', ticker: 'PSA', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'Simon Property Group', ticker: 'SPG', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'Welltower', ticker: 'WELL', marked: 'us', bors: 'NYSE', sektor: 'eiendom' },
  { navn: 'APA Corporation', ticker: 'APA', marked: 'us', bors: 'NASDAQ', sektor: 'energi' },
  { navn: 'Baker Hughes', ticker: 'BKR', marked: 'us', bors: 'NASDAQ', sektor: 'energi' },
  { navn: 'ConocoPhillips', ticker: 'COP', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Devon Energy', ticker: 'DVN', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'EOG Resources', ticker: 'EOG', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Kinder Morgan', ticker: 'KMI', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Marathon Petroleum', ticker: 'MPC', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Phillips 66', ticker: 'PSX', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'SLB (Schlumberger)', ticker: 'SLB', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Valero Energy', ticker: 'VLO', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Williams Companies', ticker: 'WMB', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'AES Corporation', ticker: 'AES', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Dominion Energy', ticker: 'D', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Duke Energy', ticker: 'DUK', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Consolidated Edison', ticker: 'ED', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Edison International', ticker: 'EIX', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Entergy', ticker: 'ETR', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Exelon', ticker: 'EXC', marked: 'us', bors: 'NASDAQ', sektor: 'energi' },
  { navn: 'Public Service Enterprise Group', ticker: 'PEG', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Southern Company', ticker: 'SO', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Sempra', ticker: 'SRE', marked: 'us', bors: 'NYSE', sektor: 'energi' },
  { navn: 'Xcel Energy', ticker: 'XEL', marked: 'us', bors: 'NASDAQ', sektor: 'energi' },
  { navn: 'First Solar', ticker: 'FSLR', marked: 'us', bors: 'NASDAQ', sektor: 'fornybar' },
  { navn: 'NextEra Energy', ticker: 'NEE', marked: 'us', bors: 'NYSE', sektor: 'fornybar' },
  { navn: 'Air Products and Chemicals', ticker: 'APD', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Albemarle', ticker: 'ALB', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'CF Industries', ticker: 'CF', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'DuPont de Nemours', ticker: 'DD', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Dow Inc.', ticker: 'DOW', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Ecolab', ticker: 'ECL', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Freeport-McMoRan', ticker: 'FCX', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Linde plc', ticker: 'LIN', marked: 'us', bors: 'NASDAQ', sektor: 'industri' },
  { navn: 'LyondellBasell', ticker: 'LYB', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Martin Marietta Materials', ticker: 'MLM', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Newmont', ticker: 'NEM', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Vulcan Materials', ticker: 'VMC', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: '3M', ticker: 'MMM', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'A. O. Smith', ticker: 'AOS', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Automatic Data Processing', ticker: 'ADP', marked: 'us', bors: 'NASDAQ', sektor: 'industri' },
  { navn: 'Axon Enterprise', ticker: 'AXON', marked: 'us', bors: 'NASDAQ', sektor: 'industri' },
  { navn: 'Carrier Global', ticker: 'CARR', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Cummins', ticker: 'CMI', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'CSX Corporation', ticker: 'CSX', marked: 'us', bors: 'NASDAQ', sektor: 'industri' },
  { navn: 'Cintas', ticker: 'CTAS', marked: 'us', bors: 'NASDAQ', sektor: 'industri' },
  { navn: 'Deere & Company', ticker: 'DE', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Emerson Electric', ticker: 'EMR', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Eaton Corporation', ticker: 'ETN', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'FedEx', ticker: 'FDX', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'General Dynamics', ticker: 'GD', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Illinois Tool Works', ticker: 'ITW', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Lockheed Martin', ticker: 'LMT', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Northrop Grumman', ticker: 'NOC', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'RTX Corporation', ticker: 'RTX', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'Union Pacific', ticker: 'UNP', marked: 'us', bors: 'NYSE', sektor: 'industri' },
  { navn: 'United Parcel Service', ticker: 'UPS', marked: 'us', bors: 'NYSE', sektor: 'industri' },

  // ---- Asia (ADR der det finnes, ellers hjemmebørs) ----
  { navn: 'Taiwan Semiconductor (ADR)', ticker: 'TSM', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Alibaba (ADR)', ticker: 'BABA', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'forbruk' },
  { navn: 'JD.com (ADR)', ticker: 'JD', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'forbruk' },
  { navn: 'PDD Holdings (ADR)', ticker: 'PDD', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'forbruk' },
  { navn: 'Baidu (ADR)', ticker: 'BIDU', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'NetEase (ADR)', ticker: 'NTES', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'Tencent Holdings', ticker: '0700.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'teknologi' },
  { navn: 'BYD', ticker: '1211.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'industri' },
  { navn: 'Sony Group (ADR)', ticker: 'SONY', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Toyota Motor (ADR)', ticker: 'TM', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'industri' },
  { navn: 'Honda Motor (ADR)', ticker: 'HMC', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'industri' },
  { navn: 'Mitsubishi UFJ Financial (ADR)', ticker: 'MUFG', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Sumitomo Mitsui Financial (ADR)', ticker: 'SMFG', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Samsung Electronics', ticker: '005930.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'POSCO Holdings (ADR)', ticker: 'PKX', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'industri' },
  { navn: 'KB Financial Group (ADR)', ticker: 'KB', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Infosys (ADR)', ticker: 'INFY', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Wipro (ADR)', ticker: 'WIT', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Tata Consultancy Services', ticker: 'TCS.NS', marked: 'asia', bors: 'India', sektor: 'teknologi' },
  { navn: 'HDFC Bank (ADR)', ticker: 'HDB', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'ICICI Bank (ADR)', ticker: 'IBN', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Reliance Industries', ticker: 'RELIANCE.NS', marked: 'asia', bors: 'India', sektor: 'energi' },
  { navn: 'NIO (ADR)', ticker: 'NIO', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'industri' },
  { navn: 'Li Auto (ADR)', ticker: 'LI', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'industri' },
  { navn: 'XPeng (ADR)', ticker: 'XPEV', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'industri' },
  { navn: 'Bilibili (ADR)', ticker: 'BILI', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'Tencent Music Entertainment (ADR)', ticker: 'TME', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'TAL Education Group (ADR)', ticker: 'TAL', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'forbruk' },
  { navn: 'New Oriental Education (ADR)', ticker: 'EDU', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'forbruk' },
  { navn: 'ZTO Express (ADR)', ticker: 'ZTO', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'industri' },
  { navn: 'Vipshop Holdings (ADR)', ticker: 'VIPS', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'forbruk' },
  { navn: 'H World Group (ADR)', ticker: 'HTHT', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'forbruk' },
  { navn: 'KE Holdings (ADR)', ticker: 'BEKE', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'eiendom' },
  { navn: 'Autohome (ADR)', ticker: 'ATHM', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'forbruk' },
  { navn: 'iQIYI (ADR)', ticker: 'IQ', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'HUYA (ADR)', ticker: 'HUYA', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Hello Group (ADR)', ticker: 'MOMO', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'GDS Holdings (ADR)', ticker: 'GDS', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'Weibo (ADR)', ticker: 'WB', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'MINISO Group (ADR)', ticker: 'MNSO', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'forbruk' },
  { navn: 'Futu Holdings (ADR)', ticker: 'FUTU', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'finans' },
  { navn: 'UP Fintech / Tiger Brokers (ADR)', ticker: 'TIGR', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'finans' },
  { navn: 'Qfin Holdings (ADR)', ticker: 'QFIN', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'finans' },
  { navn: 'LexinFintech Holdings (ADR)', ticker: 'LX', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'finans' },
  { navn: 'Full Truck Alliance (ADR)', ticker: 'YMM', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'industri' },
  { navn: 'Niu Technologies (ADR)', ticker: 'NIU', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'forbruk' },
  { navn: 'Kingsoft Cloud Holdings (ADR)', ticker: 'KC', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'Canaan (ADR)', ticker: 'CAN', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'Trip.com Group (ADR)', ticker: 'TCOM', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'forbruk' },
  { navn: 'Alibaba Group', ticker: '9988.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'teknologi' },
  { navn: 'Meituan', ticker: '3690.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'teknologi' },
  { navn: 'Xiaomi', ticker: '1810.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'teknologi' },
  { navn: 'Kuaishou Technology', ticker: '1024.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'teknologi' },
  { navn: 'Sunny Optical Technology', ticker: '2382.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'teknologi' },
  { navn: 'Ping An Insurance', ticker: '2318.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'HSBC Holdings', ticker: '0005.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'Hong Kong Exchanges and Clearing', ticker: '0388.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'China Construction Bank', ticker: '0939.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'Industrial and Commercial Bank of China', ticker: '1398.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'Bank of China', ticker: '3988.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'China Life Insurance', ticker: '2628.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'AIA Group', ticker: '1299.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'finans' },
  { navn: 'Sun Hung Kai Properties', ticker: '0016.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'eiendom' },
  { navn: 'Henderson Land Development', ticker: '0012.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'eiendom' },
  { navn: 'China Overseas Land & Investment', ticker: '0688.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'eiendom' },
  { navn: 'China Resources Land', ticker: '1109.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'eiendom' },
  { navn: 'CK Hutchison Holdings', ticker: '0001.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'industri' },
  { navn: 'MTR Corporation', ticker: '0066.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'industri' },
  { navn: 'Techtronic Industries', ticker: '0669.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'industri' },
  { navn: 'CNOOC', ticker: '0883.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'energi' },
  { navn: 'PetroChina', ticker: '0857.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'energi' },
  { navn: 'Sinopec Corp', ticker: '0386.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'energi' },
  { navn: 'China Shenhua Energy', ticker: '1088.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'energi' },
  { navn: 'CLP Holdings', ticker: '0002.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'energi' },
  { navn: 'Hong Kong and China Gas', ticker: '0003.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'energi' },
  { navn: 'Power Assets Holdings', ticker: '0006.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'energi' },
  { navn: 'China Unicom', ticker: '0762.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'telekom' },
  { navn: 'China Mobile', ticker: '0941.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'telekom' },
  { navn: 'Sands China', ticker: '1928.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Anta Sports Products', ticker: '2020.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Chow Tai Fook Jewellery', ticker: '1929.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Li Ning', ticker: '2331.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Nongfu Spring', ticker: '9633.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Haidilao International', ticker: '6862.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Geely Auto', ticker: '0175.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'China Resources Beer', ticker: '0291.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Midea Group', ticker: '0300.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Mengniu Dairy', ticker: '2319.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'Budweiser Brewing APAC', ticker: '1876.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'forbruk' },
  { navn: 'CSPC Pharmaceutical Group', ticker: '1093.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'helse' },
  { navn: 'WuXi Biologics', ticker: '2269.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'helse' },
  { navn: 'WuXi AppTec', ticker: '2359.HK', marked: 'asia', bors: 'Hong Kong', sektor: 'helse' },
  { navn: 'Canon (ADR)', ticker: 'CAJ', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Kyocera (ADR)', ticker: 'KYO', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Mizuho Financial (ADR)', ticker: 'MFG', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Nomura Holdings (ADR)', ticker: 'NMR', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Orix Corporation (ADR)', ticker: 'IX', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Takeda Pharmaceutical (ADR)', ticker: 'TAK', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'helse' },
  { navn: 'Nintendo', ticker: '7974.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'SoftBank Group', ticker: '9984.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Recruit Holdings', ticker: '6098.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Tokyo Electron', ticker: '8035.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Panasonic Holdings', ticker: '6752.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Murata Manufacturing', ticker: '6981.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Mitsubishi Electric', ticker: '6503.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Rakuten Group', ticker: '4755.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Advantest', ticker: '6857.T', marked: 'asia', bors: 'Japan', sektor: 'teknologi' },
  { navn: 'Fast Retailing', ticker: '9983.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Seven & I Holdings', ticker: '3382.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Suzuki Motor', ticker: '7269.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Subaru', ticker: '7270.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Asahi Group Holdings', ticker: '2502.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Kikkoman', ticker: '2801.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Japan Tobacco', ticker: '2914.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Aeon Co.', ticker: '8267.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'Nitori Holdings', ticker: '9843.T', marked: 'asia', bors: 'Japan', sektor: 'forbruk' },
  { navn: 'KDDI', ticker: '9433.T', marked: 'asia', bors: 'Japan', sektor: 'telekom' },
  { navn: 'Nippon Telegraph and Telephone', ticker: '9432.T', marked: 'asia', bors: 'Japan', sektor: 'telekom' },
  { navn: 'Chugai Pharmaceutical', ticker: '4519.T', marked: 'asia', bors: 'Japan', sektor: 'helse' },
  { navn: 'Astellas Pharma', ticker: '4503.T', marked: 'asia', bors: 'Japan', sektor: 'helse' },
  { navn: 'Daiichi Sankyo', ticker: '4568.T', marked: 'asia', bors: 'Japan', sektor: 'helse' },
  { navn: 'Eisai', ticker: '4523.T', marked: 'asia', bors: 'Japan', sektor: 'helse' },
  { navn: 'Terumo', ticker: '4543.T', marked: 'asia', bors: 'Japan', sektor: 'helse' },
  { navn: 'Hoya Corporation', ticker: '7741.T', marked: 'asia', bors: 'Japan', sektor: 'helse' },
  { navn: 'Sumitomo Mitsui Trust Holdings', ticker: '8309.T', marked: 'asia', bors: 'Japan', sektor: 'finans' },
  { navn: 'Dai-ichi Life Insurance', ticker: '8750.T', marked: 'asia', bors: 'Japan', sektor: 'finans' },
  { navn: 'Tokio Marine Holdings', ticker: '8766.T', marked: 'asia', bors: 'Japan', sektor: 'finans' },
  { navn: 'Daiwa Securities Group', ticker: '8601.T', marked: 'asia', bors: 'Japan', sektor: 'finans' },
  { navn: 'Japan Exchange Group', ticker: '8697.T', marked: 'asia', bors: 'Japan', sektor: 'finans' },
  { navn: 'Central Japan Railway', ticker: '9022.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'East Japan Railway', ticker: '9020.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'ANA Holdings', ticker: '9202.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Mitsubishi Corporation', ticker: '8058.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Mitsui & Co.', ticker: '8031.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Itochu Corporation', ticker: '8001.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Nippon Steel', ticker: '5401.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Denso', ticker: '6902.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Fanuc', ticker: '6954.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Bridgestone', ticker: '5108.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Shin-Etsu Chemical', ticker: '4063.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Daikin Industries', ticker: '6367.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Hitachi', ticker: '6501.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Nidec', ticker: '6594.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Komatsu', ticker: '6301.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'Mitsubishi Heavy Industries', ticker: '7011.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'JFE Holdings', ticker: '5411.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'AGC Inc.', ticker: '5201.T', marked: 'asia', bors: 'Japan', sektor: 'industri' },
  { navn: 'SK Hynix', ticker: '000660.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'Naver Corporation', ticker: '035420.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'LG Electronics', ticker: '066570.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'Samsung Electro-Mechanics', ticker: '009150.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'Samsung SDS', ticker: '018260.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'NCsoft', ticker: '036570.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'Netmarble', ticker: '251270.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'Kakao Corp', ticker: '035720.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'Krafton', ticker: '259960.KS', marked: 'asia', bors: 'Korea', sektor: 'teknologi' },
  { navn: 'Samsung Biologics', ticker: '207940.KS', marked: 'asia', bors: 'Korea', sektor: 'helse' },
  { navn: 'Celltrion', ticker: '068270.KS', marked: 'asia', bors: 'Korea', sektor: 'helse' },
  { navn: 'Hyundai Motor Company', ticker: '005380.KS', marked: 'asia', bors: 'Korea', sektor: 'forbruk' },
  { navn: 'Kia Corporation', ticker: '000270.KS', marked: 'asia', bors: 'Korea', sektor: 'forbruk' },
  { navn: 'Samsung Life Insurance', ticker: '032830.KS', marked: 'asia', bors: 'Korea', sektor: 'finans' },
  { navn: 'Samsung Fire & Marine Insurance', ticker: '000810.KS', marked: 'asia', bors: 'Korea', sektor: 'finans' },
  { navn: 'LG Energy Solution', ticker: '373220.KS', marked: 'asia', bors: 'Korea', sektor: 'fornybar' },
  { navn: 'Samsung SDI', ticker: '006400.KS', marked: 'asia', bors: 'Korea', sektor: 'fornybar' },
  { navn: 'SK Innovation', ticker: '096770.KS', marked: 'asia', bors: 'Korea', sektor: 'energi' },
  { navn: 'LG Chem', ticker: '051910.KS', marked: 'asia', bors: 'Korea', sektor: 'industri' },
  { navn: 'Korea Zinc', ticker: '010130.KS', marked: 'asia', bors: 'Korea', sektor: 'industri' },
  { navn: 'Hanwha Aerospace', ticker: '012450.KS', marked: 'asia', bors: 'Korea', sektor: 'industri' },
  { navn: 'Korea Electric Power (ADR)', ticker: 'KEP', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'energi' },
  { navn: 'Shinhan Financial Group (ADR)', ticker: 'SHG', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'LG Display (ADR)', ticker: 'LPL', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'SK Telecom (ADR)', ticker: 'SKM', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'telekom' },
  { navn: 'KT Corporation (ADR)', ticker: 'KT', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'telekom' },
  { navn: 'Woori Financial Group (ADR)', ticker: 'WF', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'finans' },
  { navn: 'Gravity Co. (ADR)', ticker: 'GRVY', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'HCL Technologies', ticker: 'HCLTECH.NS', marked: 'asia', bors: 'India', sektor: 'teknologi' },
  { navn: 'Tech Mahindra', ticker: 'TECHM.NS', marked: 'asia', bors: 'India', sektor: 'teknologi' },
  { navn: 'Bajaj Finance', ticker: 'BAJFINANCE.NS', marked: 'asia', bors: 'India', sektor: 'finans' },
  { navn: 'Bajaj Finserv', ticker: 'BAJAJFINSV.NS', marked: 'asia', bors: 'India', sektor: 'finans' },
  { navn: 'Kotak Mahindra Bank', ticker: 'KOTAKBANK.NS', marked: 'asia', bors: 'India', sektor: 'finans' },
  { navn: 'Axis Bank', ticker: 'AXISBANK.NS', marked: 'asia', bors: 'India', sektor: 'finans' },
  { navn: 'State Bank of India', ticker: 'SBIN.NS', marked: 'asia', bors: 'India', sektor: 'finans' },
  { navn: 'HDFC Life Insurance', ticker: 'HDFCLIFE.NS', marked: 'asia', bors: 'India', sektor: 'finans' },
  { navn: 'SBI Life Insurance', ticker: 'SBILIFE.NS', marked: 'asia', bors: 'India', sektor: 'finans' },
  { navn: 'Bharti Airtel', ticker: 'BHARTIARTL.NS', marked: 'asia', bors: 'India', sektor: 'telekom' },
  { navn: 'ITC Limited', ticker: 'ITC.NS', marked: 'asia', bors: 'India', sektor: 'forbruk' },
  { navn: 'Hindustan Unilever', ticker: 'HINDUNILVR.NS', marked: 'asia', bors: 'India', sektor: 'forbruk' },
  { navn: 'Asian Paints', ticker: 'ASIANPAINT.NS', marked: 'asia', bors: 'India', sektor: 'forbruk' },
  { navn: 'Maruti Suzuki India', ticker: 'MARUTI.NS', marked: 'asia', bors: 'India', sektor: 'forbruk' },
  { navn: 'Titan Company', ticker: 'TITAN.NS', marked: 'asia', bors: 'India', sektor: 'forbruk' },
  { navn: 'Sun Pharmaceutical Industries', ticker: 'SUNPHARMA.NS', marked: 'asia', bors: 'India', sektor: 'helse' },
  { navn: 'Cipla', ticker: 'CIPLA.NS', marked: 'asia', bors: 'India', sektor: 'helse' },
  { navn: 'Larsen & Toubro', ticker: 'LT.NS', marked: 'asia', bors: 'India', sektor: 'industri' },
  { navn: 'Adani Enterprises', ticker: 'ADANIENT.NS', marked: 'asia', bors: 'India', sektor: 'industri' },
  { navn: 'Tata Steel', ticker: 'TATASTEEL.NS', marked: 'asia', bors: 'India', sektor: 'industri' },
  { navn: 'JSW Steel', ticker: 'JSWSTEEL.NS', marked: 'asia', bors: 'India', sektor: 'industri' },
  { navn: 'Grasim Industries', ticker: 'GRASIM.NS', marked: 'asia', bors: 'India', sektor: 'industri' },
  { navn: 'UltraTech Cement', ticker: 'ULTRACEMCO.NS', marked: 'asia', bors: 'India', sektor: 'industri' },
  { navn: 'NTPC Limited', ticker: 'NTPC.NS', marked: 'asia', bors: 'India', sektor: 'energi' },
  { navn: 'Power Grid Corporation of India', ticker: 'POWERGRID.NS', marked: 'asia', bors: 'India', sektor: 'energi' },
  { navn: 'Oil and Natural Gas Corporation', ticker: 'ONGC.NS', marked: 'asia', bors: 'India', sektor: 'energi' },
  { navn: 'Coal India', ticker: 'COALINDIA.NS', marked: 'asia', bors: 'India', sektor: 'energi' },
  { navn: "Dr. Reddy's Laboratories (ADR)", ticker: 'RDY', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'helse' },
  { navn: 'WNS Holdings (ADR)', ticker: 'WNS', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Sify Technologies (ADR)', ticker: 'SIFY', marked: 'asia', bors: 'NASDAQ (ADR)', sektor: 'teknologi' },
  { navn: 'United Microelectronics (ADR)', ticker: 'UMC', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'ASE Technology Holding (ADR)', ticker: 'ASX', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'teknologi' },
  { navn: 'Chunghwa Telecom (ADR)', ticker: 'CHT', marked: 'asia', bors: 'NYSE (ADR)', sektor: 'telekom' },
  { navn: 'MediaTek', ticker: '2454.TW', marked: 'asia', bors: 'Taiwan', sektor: 'teknologi' },
  { navn: 'Hon Hai Precision Industry (Foxconn)', ticker: '2317.TW', marked: 'asia', bors: 'Taiwan', sektor: 'teknologi' },
  { navn: 'Delta Electronics', ticker: '2308.TW', marked: 'asia', bors: 'Taiwan', sektor: 'teknologi' },
  { navn: 'Formosa Plastics', ticker: '1301.TW', marked: 'asia', bors: 'Taiwan', sektor: 'industri' },
  { navn: 'Nan Ya Plastics', ticker: '1303.TW', marked: 'asia', bors: 'Taiwan', sektor: 'industri' },
  { navn: 'China Steel Corporation', ticker: '2002.TW', marked: 'asia', bors: 'Taiwan', sektor: 'industri' },
  { navn: 'Fubon Financial Holding', ticker: '2881.TW', marked: 'asia', bors: 'Taiwan', sektor: 'finans' },
  { navn: 'Cathay Financial Holding', ticker: '2882.TW', marked: 'asia', bors: 'Taiwan', sektor: 'finans' },
  { navn: 'CTBC Financial Holding', ticker: '2891.TW', marked: 'asia', bors: 'Taiwan', sektor: 'finans' },
  { navn: 'Mega Financial Holding', ticker: '2886.TW', marked: 'asia', bors: 'Taiwan', sektor: 'finans' },
  { navn: 'Taiwan Mobile', ticker: '3045.TW', marked: 'asia', bors: 'Taiwan', sektor: 'telekom' },
  { navn: 'Evergreen Marine', ticker: '2603.TW', marked: 'asia', bors: 'Taiwan', sektor: 'shipping' },
  { navn: 'Yang Ming Marine Transport', ticker: '2609.TW', marked: 'asia', bors: 'Taiwan', sektor: 'shipping' },
  { navn: 'Wan Hai Lines', ticker: '2615.TW', marked: 'asia', bors: 'Taiwan', sektor: 'shipping' },
]
